server {
    listen 80;
    root /usr/share/nginx/html;
    include /etc/nginx/mime.types;
    types { application/wasm wasm; }
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache";
        add_header Content-Security-Policy "frame-ancestors 'self'" always;
    }
}
