using Aurora.Contracts;
using Aurora.Modules.Routing;
using Aurora.Modules.Routing.Optimization;
using Aurora.Infrastructure.Data;
using Aurora.Infrastructure.Tenancy;
using Npgsql;
using Dapper;
using System.Text.Json.Nodes;

var count=0;
void Check(bool value,string name) { if(!value)throw new Exception(name);Console.WriteLine("PASS "+name);count++; }
void Reject(Action action,string name) { try { action(); } catch(FormatException) { Check(true,name);return; }throw new Exception(name); }
var json=File.ReadAllText(Path.Combine(AppContext.BaseDirectory,"sample.json"));
var root=RoutingInput.Parse(json);
var ids=OrderWorkspace.OrderIds(json);
var selected=OrderWorkspace.SelectOrders(json,[ids[0],ids[1]]);
Check(OrderWorkspace.OrderIds(selected).Length==2,"only selected orders enter request");
Check(OrderWorkspace.OrderIds(json).Length==3,"original input unchanged");
Check(RoutingInput.Parse(selected)["vehicles"]!.ToJsonString()==root["vehicles"]!.ToJsonString(),"fleet constraints preserved");
Reject(()=>OrderWorkspace.SelectOrders(json,["unknown"]),"unknown orders rejected");
Reject(()=>OrderWorkspace.SelectOrders(json,[ids[0],ids[0]]),"duplicate selection rejected");
Reject(()=>OrderWorkspace.SelectOrders(json,[]),"empty selection rejected");
var location=RoutingInput.Text(root["orders"]!["deliveries"]![0]!["delivery"]!["locationId"])!;
var truck=RoutingInput.Text(root["vehicles"]![0]!["id"])!;
var raw=new JsonObject { ["status"]="SUCCEEDED",["metrics"]=new JsonObject { ["numberOfScheduledOrders"]=1,["numberOfUnscheduledOrders"]=2 },["routes"]=new JsonArray(new JsonObject {
 ["vehicleId"]=truck,["stops"]=new JsonArray(new JsonObject { ["locationId"]=location,["appointments"]=new JsonArray(new JsonObject { ["tasks"]=new JsonArray(new JsonObject { ["orderId"]=ids[0],["type"]="DELIVERY" }) }) }) }) };
var result=OptimizationService.Describe("sample.json",json,new PtvRun("test","SUCCEEDED",new PtvResponse(200,"OK",raw.ToJsonString()),TimeSpan.FromSeconds(1)));
Check(OrderWorkspace.Assignments(result,ids).Single().Orders.Single()==ids[0],"saved assignment uses parsed provider stop order");
Reject(()=>OrderWorkspace.Assignments(result,[ids[1]]),"unknown result order rejected");
Reject(()=>OrderWorkspace.Assignments(result with { Routes=result.Routes.Concat(result.Routes).ToArray() },ids),"duplicate result assignment rejected");
Reject(()=>OrderWorkspace.Assignments(result with { Status="RUNNING" },ids),"interim result cannot be finished");
var terminal=RoutingInput.Text(root["reporting"]?["terminal"])!;
var type=new EquipmentTypeDto {Code="CHECK",Description="Saved truck",Weight=12345,PerHour=42};
var unit=new EquipmentUnitDto {Id=truck,TypeCode=type.Code,Terminal=terminal,UseForRouting=true,ShiftStart="20:00",ShiftEnd="06:00"};
var fleet=new EquipmentCatalogDto([type],[unit]);
var fleetInput=FleetPlanning.Build(selected,fleet);
Check(RoutingInput.Items(RoutingInput.Parse(fleetInput)["vehicles"]).Count()==1,"fleet comes from saved truck records, not file vehicles");
var built=RoutingInput.Parse(fleetInput)["vehicles"]![0]!;
Check(RoutingInput.Time(built["end"]!["latestEndTime"])>RoutingInput.Time(built["start"]!["earliestStartTime"]),"overnight shift advances return date");
var edited=RoutingInput.Parse(fleetInput);edited["vehicles"]![0]!["costs"]!["perHour"]=0;
var canonical=RoutingInput.Parse(FleetPlanning.ApplySavedFleet(edited.ToJsonString(),fleet,terminal));
Check(canonical["vehicles"]![0]!["costs"]!["perHour"]!.GetValue<double>()==42,"server restores saved fleet costs");
Reject(()=>FleetPlanning.Build(json,new([type],[])),"empty fleet does not fall back to file trucks");
Reject(()=>FleetPlanning.ApplySavedFleet(fleetInput,fleet,"OTHER"),"another terminal's trucks are rejected");
unit.Available=false;
Reject(()=>FleetPlanning.ApplySavedFleet(fleetInput,fleet,terminal),"unavailable saved truck cannot optimize");
unit.Available=true;
Check(WorkspaceOrderStatus.Label(WorkspaceOrderStatus.Ready)=="Ready to Ship" && WorkspaceOrderStatus.All.Contains("AwaitingAppointment"),"Nova lifecycle labels include requested ready state");
var connection=Environment.GetEnvironmentVariable("WORKSPACE_CHECK_CONNECTION");
if(connection is not null)
{
 var settings=new NpgsqlConnectionStringBuilder(connection);
 if(!settings.Database!.StartsWith("aurora_workspace_checks_"))throw new Exception("Integration checks require an isolated checks database.");
 await using var source=NpgsqlDataSource.Create(connection);
 var tenant=new TestTenant(Guid.NewGuid());
 var factory=new NpgsqlConnectionFactory(source,tenant);
 await using(var db=await factory.OpenConnectionAsync()) await db.ExecuteAsync("INSERT INTO tenant(id,name,slug) VALUES (@Id,'Workspace checks',@Slug)",new { Id=tenant.TenantIdOrNull,Slug=Guid.NewGuid().ToString("N") });
 var store=new OrderWorkspace(factory,tenant);
 await store.Import(new("Fixture",json),default);
 await store.Import(new("Fixture",json),default);
 var import=(await store.Sources(default)).Single();
 var orders=(await store.Orders(import.Id,null,null,null,default)).ToArray();
 Check(orders.Length==3,"import idempotency and order persistence");
 Check((await store.Orders(import.Id,orders[0].ScheduledAt,orders[0].ScheduledAt,null,default)).Any(),"inclusive datetime filter");
 Check(!(await store.Orders(import.Id,null,null,"Routed",default)).Any(),"initial status is available");
 var equipment=new EquipmentStore(factory,tenant);
 await equipment.AddMissing(fleet,default);
 Check((await equipment.List(default)).Units.Single().UseForRouting,"planning eligibility persists in tenant equipment table");
 var draft=await store.CreateDraft(new(import.Id,ids),"owner",default);
 Check((await store.Draft(draft.Id,"owner",default)).Id==draft.Id,"draft recovery");
 try { await store.Draft(draft.Id,"other",default);throw new Exception("owner isolation"); }catch(KeyNotFoundException){Check(true,"draft owner isolation");}
 var otherTenant=new TestTenant(Guid.NewGuid());
 var otherFactory=new NpgsqlConnectionFactory(source,otherTenant);
 var other=new OrderWorkspace(otherFactory,otherTenant);
 await using(var hidden=await otherFactory.OpenConnectionAsync()) Check(await hidden.ExecuteScalarAsync<int>("SELECT count(*) FROM aurora_order")==0,"database RLS hides orders without a tenant WHERE clause");
 Check(!(await other.Sources(default)).Any(),"cross tenant data hidden");
 Check(!(await new EquipmentStore(otherFactory,otherTenant).List(default)).Units.Any(),"another tenant cannot read saved trucks");
 var tenantFleetDraft=RoutingInput.Parse(draft.RequestJson);
 Check(tenantFleetDraft["vehicles"]!.AsArray().Count==1,"database draft contains only eligible tenant fleet");
 var conflicting=await store.CreateDraft(new(import.Id,ids),"owner",default);
 var session=Guid.NewGuid();
 var manifests=await store.Finish(draft.Id,session,"owner",result,default);
 Check(manifests.Count==1 && manifests[0].Route.Pros.Single().ProNumber==ids[0],"one persisted manifest per route");
 Check((await store.Orders(import.Id,null,null,"ReadyToRoute",default)).Count()==2,"unscheduled orders remain available");
 Check((await store.Finish(draft.Id,session,"owner",result,default)).Single().Id==manifests[0].Id,"finish retry returns same manifest");
 try {await store.Finish(conflicting.Id,Guid.NewGuid(),"owner",result,default);throw new Exception("conflict missing");}catch(FormatException){Check(true,"overlapping plan cannot duplicate assignment");}
 Check((await store.Manifests(default)).Count==1,"conflicting finish is atomic");
 var details=new ManifestDetailsDto {BillToCode="ACCT-100",BillToName="Test Bill To",Carrier="Test Carrier",Driver="Test Driver",Notes="Handle carefully"};
 var editedManifest=await store.UpdateManifest(manifests[0].Id,new(details,0),default);
 Check(editedManifest.Details?.BillToCode=="ACCT-100" && editedManifest.Revision==1,"manifest details persist with revision");
 Check(System.Text.Json.JsonSerializer.Serialize(editedManifest.Route)==System.Text.Json.JsonSerializer.Serialize(manifests[0].Route),"editing details preserves optimized route snapshot");
 Check((await store.Manifests(default)).Single().Details?.Carrier=="Test Carrier","details survive reload");
 try {await store.UpdateManifest(editedManifest.Id,new(details,0),default);throw new Exception("stale update accepted");}catch(FormatException){Check(true,"stale manifest edit rejected");}
 try {await other.UpdateManifest(editedManifest.Id,new(details,1),default);throw new Exception("cross tenant edit accepted");}catch(KeyNotFoundException){Check(true,"cross tenant manifest edit rejected");}
 try {await store.UpdateManifest(editedManifest.Id,new(new ManifestDetailsDto {Notes=new string('x',4001)},1),default);throw new Exception("invalid details accepted");}catch(FormatException){Check(true,"oversized notes rejected");}


 var tms=new TmsStore(factory,tenant); var hiddenTms=new TmsStore(otherFactory,otherTenant);
 async Task Fails(Func<Task> action,string name){try{await action();}catch(Exception ex) when(ex is FormatException or KeyNotFoundException or PostgresException){Check(true,name);return;}throw new Exception(name);}
 var terminals=new TerminalStore(factory,tenant);
 var hiddenTerminals=new TerminalStore(otherFactory,otherTenant);
 var importedTerminal=(await terminals.List(default)).Single();
 Check(importedTerminal.Code==terminal,"import creates terminal directory entry");
 Check((await tms.Orders(null,null,null,null,null,default)).All(o=>o.TerminalId==importedTerminal.Id && o.TerminalCode==terminal),"imported orders retain terminal assignment");
 await Fails(()=>terminals.Delete(importedTerminal.Id,0,default),"in-use terminal cannot be deleted");
 var terminalItem=new TerminalDto{Code=" CHECK-NEW ",Name=" Dispatch terminal ",Address="1 Main St",City="Boston",State="MA",PostalCode="02101",Country="US"};
 await terminals.Save(terminalItem,true,default);
 var savedTerminal=(await terminals.List(default)).Single(t=>t.Id==terminalItem.Id);
 Check(savedTerminal.Code=="CHECK-NEW" && savedTerminal.Name=="Dispatch terminal" && savedTerminal.Address=="1 Main St","terminal create and address persistence");
 await Fails(()=>terminals.Save(new(){Code="check-new",Name="Duplicate"},true,default),"terminal code uniqueness ignores case");
 await Fails(()=>terminals.Save(new(){Code=" ",Name="Missing code"},true,default),"blank terminal code rejected");
 savedTerminal.Name="Updated dispatch";await terminals.Save(savedTerminal,false,default);
 Check((await terminals.List(default)).Single(t=>t.Id==savedTerminal.Id).Name=="Updated dispatch","terminal edit persists");
 await Fails(()=>terminals.Save(savedTerminal,false,default),"stale terminal edit rejected");
 await Fails(()=>terminals.Delete(savedTerminal.Id,0,default),"stale terminal delete rejected");
 Check(!(await hiddenTerminals.List(default)).Any(),"terminal directory tenant isolation");
 await using(var hidden=await otherFactory.OpenConnectionAsync()) Check(await hidden.ExecuteScalarAsync<int>("SELECT count(*) FROM aurora_terminal")==0,"terminal RLS hides rows without tenant filter");
 savedTerminal.Revision=1;
 await Fails(()=>hiddenTerminals.Save(savedTerminal,false,default),"cross-tenant terminal edit rejected");
 await Fails(()=>hiddenTerminals.Delete(savedTerminal.Id,1,default),"cross-tenant terminal delete rejected");
 var assignedTerminalOrder=new TmsOrder{Id="TERMINAL-ORDER",Customer="Terminal check",TerminalId=savedTerminal.Id};
 await tms.SaveOrder(assignedTerminalOrder,true,default);
 var terminalOrder=(await tms.Orders(null,null,null,"TERMINAL-ORDER",null,default)).Single();
 Check((await tms.Orders(null,null,null,null,null,default,savedTerminal.Id)).Single().Id=="TERMINAL-ORDER","terminal filter returns only assigned orders");
 Check(!(await tms.Orders(null,null,null,null,null,default,Guid.NewGuid())).Any(),"unknown terminal filter returns no orders");
 Check(!(await hiddenTms.Orders(null,null,null,null,null,default,savedTerminal.Id)).Any(),"terminal filter preserves tenant isolation");
 Check(terminalOrder.TerminalId==savedTerminal.Id && terminalOrder.TerminalCode=="CHECK-NEW","order terminal round trip");
 await Fails(()=>terminals.Delete(savedTerminal.Id,1,default),"order assignment blocks terminal deletion");
 await Fails(()=>hiddenTms.SaveOrder(new(){Id="FOREIGN",Customer="Foreign",TerminalId=savedTerminal.Id},true,default),"cross-tenant terminal assignment rejected");
 await Fails(()=>tms.SaveOrder(new(){Id="INVALID",Customer="Invalid",TerminalId=Guid.NewGuid()},true,default),"unknown terminal assignment rejected");
 var mixedOrder=(await tms.Orders(null,null,null,ids[1],null,default)).Single();
 mixedOrder.TerminalId=savedTerminal.Id;await tms.SaveOrder(mixedOrder,false,default);
 await Fails(()=>store.CreateDraft(new(import.Id,[ids[1],ids[2]]),"owner",default),"mixed terminal planning rejected");
 mixedOrder.TerminalId=importedTerminal.Id;mixedOrder.Revision++;await tms.SaveOrder(mixedOrder,false,default);
 terminalOrder.TerminalId=null;await tms.SaveOrder(terminalOrder,false,default);
 Check((await tms.Orders(null,null,null,"TERMINAL-ORDER",null,default)).Single().TerminalId is null,"order terminal can be cleared");
 await terminals.Delete(savedTerminal.Id,1,default);
 Check(!(await terminals.List(default)).Any(t=>t.Id==savedTerminal.Id),"deleted terminal disappears");
 await Fails(()=>tms.SaveOrder(new(){Id="DELETED",Customer="Deleted",TerminalId=savedTerminal.Id},true,default),"deleted terminal assignment rejected");
 var shipment=new TmsOrder{Id="CRUD-100",Customer="Acme",City="Philadelphia",Address="123 Test St",Address2="Dock 2",Country="US",Shipper="Origin Co",OriginAddress="456 Origin Ave",OriginAddress2="Suite 9",OriginCity="Boston",OriginState="MA",OriginPostalCode="02101",OriginCountry="US",BillTo="Billing Co",BillToAddress="789 Accounts Rd",BillToAddress2="Floor 3",BillToCity="Toronto",BillToState="ON",BillToPostalCode="M5V 2T6",BillToCountry="CA",Pieces=5,Weight=900,ScheduledAt=DateTimeOffset.UtcNow};
 await tms.SaveOrder(shipment,true,default);
 var loaded=(await tms.Orders(null,null,null,"CRUD-100",null,default)).Single();
 Check(loaded.Address==shipment.Address && loaded.Weight==900,"manual shipment fields persist");
 Check(loaded.BillToAddress=="789 Accounts Rd" && loaded.BillToAddress2=="Floor 3" && loaded.BillToCity=="Toronto" && loaded.BillToState=="ON" && loaded.BillToPostalCode=="M5V 2T6" && loaded.BillToCountry=="CA" && loaded.OriginAddress=="456 Origin Ave" && loaded.OriginAddress2=="Suite 9" && loaded.OriginCountry=="US" && loaded.Country=="US" && loaded.Address2=="Dock 2","all three independent addresses survive database reload");
 var copied=System.Text.Json.JsonSerializer.Deserialize<TmsOrder>(System.Text.Json.JsonSerializer.Serialize(loaded))!;
 copied.CopyBillTo(true);Check(copied.BillTo=="Origin Co" && copied.BillToAddress=="456 Origin Ave" && copied.BillToAddress2=="Suite 9" && copied.BillToPostalCode=="02101","copy shipper includes complete billing address");
 copied.CopyBillTo(false);Check(copied.BillTo=="Acme" && copied.BillToAddress=="123 Test St" && copied.BillToAddress2=="Dock 2" && copied.BillToCountry=="US","copy consignee includes complete billing address");
 copied.BillToAddress="Independent edit";Check(copied.Address=="123 Test St" && copied.OriginAddress=="456 Origin Ave","billing copy stays independently editable");
 loaded.Customer="Acme edited";await tms.SaveOrder(loaded,false,default);
 await Fails(()=>tms.SaveOrder(loaded,false,default),"stale order edit rejected");
 Check(!(await hiddenTms.Orders(null,null,null,null,null,default)).Any(),"TMS order tenant isolation");
 Check(!(await tms.Orders(DateTimeOffset.UtcNow.AddDays(1),null,null,"CRUD-100",null,default)).Any(),"TMS order date filtering");
 await Fails(()=>hiddenTms.DeleteOrder(loaded.SourceId,loaded.Id,1,default),"cross tenant order delete rejected");
 var manifest=new TmsManifest{Number="TEST-100",Vehicle=truck,Details=new(){Carrier="Carrier",BillToName="Bill to"}};
 await tms.SaveManifest(manifest,true,default);
 var fresh=(await tms.Manifests(default)).Single(m=>m.Id==manifest.Id);
 Check(fresh.Details.Carrier=="Carrier" && fresh.OrderCount==0,"manual manifest created without optimization");
 var key=new TmsOrderKey(loaded.SourceId,loaded.Id);
 await tms.ChangeOrders(fresh.Id,new([key],0),false,false,default);
 loaded=(await tms.Orders(null,null,null,null,fresh.Id,default)).Single();
 Check(loaded.Status=="Routed" && loaded.ManifestNumber=="TEST-100","assignment persists and marks order Routed");
 await Fails(()=>tms.DeleteOrder(loaded.SourceId,loaded.Id,loaded.Revision,default),"assigned order cannot be deleted");
 await Fails(()=>tms.ChangeOrders(fresh.Id,new([key],0),true,false,default),"stale assignment change rejected");
 var second=new TmsManifest{Number="TEST-200"};await tms.SaveManifest(second,true,default);
 await Fails(()=>tms.ChangeOrders(second.Id,new([key],0),false,false,default),"order cannot be assigned twice");
 await Fails(()=>hiddenTms.ChangeOrders(fresh.Id,new([key],1),true,false,default),"cross tenant membership rejected");
 await tms.ChangeOrders(fresh.Id,new([key],1),true,false,default);
 loaded=(await tms.Orders(null,null,null,"CRUD-100",null,default)).Single();
 Check(loaded.Status==WorkspaceOrderStatus.Ready && loaded.ManifestId is null,"removing order returns it to Ready to Ship");
 await tms.ChangeOrders(fresh.Id,new([key],2),false,false,default);
 await tms.ChangeOrders(fresh.Id,new([],3),true,true,default);
 Check(!(await tms.Manifests(default)).Any(m=>m.Id==fresh.Id),"deleted manifest disappears");
 loaded=(await tms.Orders(null,null,null,"CRUD-100",null,default)).Single();
 Check(loaded.ManifestId is null && loaded.Status==WorkspaceOrderStatus.Ready,"manifest deletion releases orders");
 await tms.ChangeOrders(second.Id,new([key],0),false,false,default);
 var dispatch=(await tms.Manifests(default)).Single(m=>m.Id==second.Id);dispatch.Status="Dispatched";await tms.SaveManifest(dispatch,false,default);
 loaded=(await tms.Orders(null,null,null,"CRUD-100",null,default)).Single();Check(loaded.Status=="Dispatched","manifest lifecycle updates order status");
 await Fails(()=>tms.ChangeOrders(second.Id,new([],2),true,true,default),"dispatched manifest cannot be deleted");
 await Fails(()=>tms.ChangeOrders(second.Id,new([key],2),true,false,default),"dispatched assignments locked");
 await Fails(()=>tms.SaveOrder(loaded,false,default),"dispatched order edit locked");
 var disposable=new TmsOrder{Id="DELETE-ME",Customer="Temp"};await tms.SaveOrder(disposable,true,default);await tms.DeleteOrder(disposable.SourceId,disposable.Id,0,default);
 Check(!(await tms.Orders(null,null,null,"DELETE-ME",null,default)).Any(),"unassigned order delete persists");

 var customers=new CustomerStore(factory,tenant);
 var customer=new CustomerDto{Code="CUSTOMER-CHECK",Name="Customer check",Address="12 Main Street"};
 await customers.Save(customer,true,default);
 var savedCustomer=(await customers.List(default)).Single(c=>c.Code==customer.Code);
 Check(savedCustomer.Address==customer.Address,"customer address persists");
 savedCustomer.Phone="555-0100";await customers.Save(savedCustomer,false,default);
 await Fails(()=>customers.Save(savedCustomer,false,default),"stale customer edit rejected");
 var hiddenCustomers=new CustomerStore(otherFactory,otherTenant);
 Check(!(await hiddenCustomers.List(default)).Any(),"customer tenant isolation");
 var customerOrder=new TmsOrder{Id="CUSTOMER-ORDER",Customer=customer.Name,CustomerId=savedCustomer.Id};
 await tms.SaveOrder(customerOrder,true,default);
 Check((await tms.Orders(null,null,null,"CUSTOMER-ORDER",null,default)).Single().CustomerCode==customer.Code,"order customer link persists");
 await Fails(()=>customers.Delete(savedCustomer.Id,1,default),"referenced customer deletion blocked");
 await Fails(()=>hiddenTms.SaveOrder(new(){Id="FOREIGN-CUSTOMER",Customer="Foreign",CustomerId=savedCustomer.Id},true,default),"foreign customer assignment rejected");
 await tms.DeleteOrder(customerOrder.SourceId,customerOrder.Id,0,default);
 await customers.Delete(savedCustomer.Id,1,default);
 Check(!(await customers.List(default)).Any(c=>c.Id==savedCustomer.Id),"customer delete persists");
 var importText=File.ReadAllText("src/Aurora.Client/wwwroot/samples/workspace-import.json");
 var replacement=WorkspaceImport.Parse(importText);
 var importer=new WorkspaceImportStore(factory,tenant);
 var oldCount=(await tms.Orders(null,null,null,null,null,default)).Count;
 await importer.Execute(replacement,false,default);
 Check((await tms.Orders(null,null,null,null,null,default)).Count==oldCount,"import validation does not mutate orders");
 await using(var db=await otherFactory.OpenConnectionAsync()) await db.ExecuteAsync("INSERT INTO tenant(id,name,slug) VALUES (@Id,'Other checks',@Slug)",new { Id=otherTenant.TenantIdOrNull,Slug=Guid.NewGuid().ToString("N") });
 var foreignOrder=new TmsOrder{Id="KEEP-OTHER-COMPANY",Customer="Untouched"};await hiddenTms.SaveOrder(foreignOrder,true,default);
 replacement.Customers[0].Address="\0";
 try {await importer.Execute(replacement,true,default);throw new Exception("Expected SQL rejection");} catch(PostgresException) {Check(true,"late import failure rejected");}
 Check((await tms.Orders(null,null,null,null,null,default)).Count==oldCount,"failed import rolls back deleted records");
 replacement=WorkspaceImport.Parse(importText);await importer.Execute(replacement,true,default);
 Check((await tms.Orders(null,null,null,null,null,default)).Count==3,"import replaces existing orders");
 Check((await customers.List(default)).Count==3 && (await terminals.List(default)).Count==1,"import replaces customers and terminals");
 Check((await tms.Manifests(default)).Single().OrderCount==1,"import preserves manifest assignments");
 Check((await hiddenTms.Orders(null,null,null,null,null,default)).Single().Id==foreignOrder.Id,"import preserves other company records");
 var importedOrder=(await tms.Orders(null,null,null,"TEST_SOUTH",null,default)).Single();
 Check(importedOrder.CustomerCode=="C002" && importedOrder.TerminalCode=="KC","import resolves customer and terminal identities");
 await store.CreateDraft(new(importedOrder.SourceId,[importedOrder.Id]),"owner",default);
 Check(true,"example imported orders support planning");
 await importer.Execute(new(){Version=1,Terminals=[],Customers=[],Orders=[],Trucks=[],Manifests=[]},true,default);
 Check(!(await customers.List(default)).Any() && !(await tms.Orders(null,null,null,null,null,default)).Any(),"empty import clears company operational records");
 if(args.Length>0) { await store.Import(new("Desktop appointment file",File.ReadAllText(args[0])),default); var desktop=(await store.Sources(default)).Single(s=>s.Name=="Desktop appointment file"); Check((await store.Orders(desktop.Id,null,null,null,default)).Count()==100,"all 100 desktop orders import with dates"); }
}
Console.WriteLine($"{count} order workspace checks passed.");
sealed record TestTenant(Guid Id) : ITenantContext { public Guid? TenantIdOrNull=>Id;public Guid? UserIdOrNull=>Guid.Empty; }

